const menu = [
  {
    project: '0209-test-new-ef-settings',
    course: 'test - copy',
    person: 'Lukasz',
    email: 'l.jarmulowicz@gmail.com',
    department: '',
    location: '',
    courseStartedDate: '',
    openedLessonsCount: '0',
    completedDate: '',
    completedLessonsCount: 0,
    totalLessonsCount: 1,
    haveNotStarted: '1',
    notOnSchedule: '1',
    haveStarted: '0',
    quizScore: 0,
    quizScoreTotal: 1,
    certificateTitle: null,
  },
  {
    project: '0903-evaluaiton1',
    course: 'evaluation',
    person: 'luk2',
    email: 'lukeon2+2@gmail.com',
    department: '',
    location: '',
    courseStartedDate: '2021-03-09 10:02:35',
    openedLessonsCount: '1',
    completedDate: '2021-03-09 10:05:03',
    completedLessonsCount: 1,
    totalLessonsCount: 1,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: '1032021-311_1',
    course: 'test - copy',
    person: 'Lukasz',
    email: 'l.jarmulowicz@gmail.com',
    department: '',
    location: '',
    courseStartedDate: '',
    openedLessonsCount: '0',
    completedDate: '',
    completedLessonsCount: 0,
    totalLessonsCount: 3,
    haveNotStarted: '1',
    notOnSchedule: '1',
    haveStarted: '0',
    quizScore: 0,
    quizScoreTotal: 2,
    certificateTitle: null,
  },
  {
    project: '1202-fewdays1',
    course: 'Teams - Effektive møter',
    person: 'luk2',
    email: 'lukeon2+2@gmail.com',
    department: '',
    location: '',
    courseStartedDate: '2021-02-15 06:11:46',
    openedLessonsCount: '1',
    completedDate: '',
    completedLessonsCount: 0,
    totalLessonsCount: 5,
    haveNotStarted: '0',
    notOnSchedule: '1',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: '1202-pr-3.10-1',
    course: 'test - copy',
    person: 'luk2',
    email: 'lukeon2+2@gmail.com',
    department: '',
    location: '',
    courseStartedDate: '2021-02-12 19:00:55',
    openedLessonsCount: '2',
    completedDate: '',
    completedLessonsCount: 1,
    totalLessonsCount: 3,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 2,
    certificateTitle: null,
  },
  {
    project: '1404-newprod1-luk',
    course: 'test - copy',
    person: 'luk2',
    email: 'lukeon2+2@gmail.com',
    department: '',
    location: '',
    courseStartedDate: '2021-04-14 15:00:55',
    openedLessonsCount: '1',
    completedDate: '',
    completedLessonsCount: 0,
    totalLessonsCount: 3,
    haveNotStarted: '0',
    notOnSchedule: '1',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 2,
    certificateTitle: null,
  },
  {
    project: '1609-prod1',
    course: 'test - copy',
    person: 'Lukasz',
    email: 'l.jarmulowicz@gmail.com',
    department: '',
    location: '',
    courseStartedDate: '2020-09-16 20:00:54',
    openedLessonsCount: '1',
    completedDate: '2020-09-16 20:01:22',
    completedLessonsCount: 1,
    totalLessonsCount: 1,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 1,
    quizScoreTotal: 1,
    certificateTitle: null,
  },
  {
    project: '20.01-3.9_1',
    course: 'Extreme quizes',
    person: 'luk2',
    email: 'lukeon2+2@gmail.com',
    department: '',
    location: '',
    courseStartedDate: '2021-01-20 16:25:48',
    openedLessonsCount: '1',
    completedDate: '2021-01-20 16:26:08',
    completedLessonsCount: 1,
    totalLessonsCount: 1,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 3,
    certificateTitle: null,
  },
  {
    project: '20.01-3.9after-mq-delete1',
    course: 'test - copy',
    person: 'Lukasz',
    email: 'l.jarmulowicz@gmail.com',
    department: '',
    location: '',
    courseStartedDate: '2021-01-20 16:42:40',
    openedLessonsCount: '2',
    completedDate: '2021-01-20 16:43:20',
    completedLessonsCount: 2,
    totalLessonsCount: 2,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 1,
    quizScoreTotal: 1,
    certificateTitle: null,
  },
  {
    project: '2912-1',
    course: 'xxxx',
    person: 'Lukasz',
    email: 'lukasz@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '',
    openedLessonsCount: '0',
    completedDate: '',
    completedLessonsCount: 0,
    totalLessonsCount: 1,
    haveNotStarted: '1',
    notOnSchedule: '1',
    haveStarted: '0',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: 'Demo of XtraMile',
    course: 'Demo for Lukasz Coding',
    person: 'Lukasz',
    email: 'l.jarmulowicz@gmail.com',
    department: '',
    location: '',
    courseStartedDate: '2019-01-25 10:10:43',
    openedLessonsCount: '1',
    completedDate: '',
    completedLessonsCount: 1,
    totalLessonsCount: 3,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 1,
    certificateTitle: null,
  },
  {
    project: 'dmarc1',
    course: 'test - copy',
    person: 'luk2',
    email: 'lukeon2+2@gmail.com',
    department: '',
    location: '',
    courseStartedDate: '',
    openedLessonsCount: '0',
    completedDate: '',
    completedLessonsCount: 0,
    totalLessonsCount: 1,
    haveNotStarted: '1',
    notOnSchedule: '1',
    haveStarted: '0',
    quizScore: 0,
    quizScoreTotal: 1,
    certificateTitle: null,
  },
  {
    project: 'dmarc1',
    course: 'test - copy',
    person: 'Lukasz',
    email: 'lukasz@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2020-10-06 04:10:12',
    openedLessonsCount: '2',
    completedDate: '',
    completedLessonsCount: 0,
    totalLessonsCount: 3,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 1,
    certificateTitle: null,
  },
  {
    project: 'dmarc1',
    course: 'test - copy',
    person: 'Lukasz',
    email: 'l.jarmulowicz@gmail.com',
    department: '',
    location: '',
    courseStartedDate: '',
    openedLessonsCount: '0',
    completedDate: '',
    completedLessonsCount: 0,
    totalLessonsCount: 1,
    haveNotStarted: '1',
    notOnSchedule: '1',
    haveStarted: '0',
    quizScore: 0,
    quizScoreTotal: 1,
    certificateTitle: null,
  },
  {
    project: 'luk1',
    course: 'Teams - Administrer medlemmer og innhold',
    person: 'luk2',
    email: 'lukeon2+2@gmail.com',
    department: '',
    location: '',
    courseStartedDate: '2020-04-08 06:08:46',
    openedLessonsCount: '4',
    completedDate: '2020-04-08 06:09:34',
    completedLessonsCount: 4,
    totalLessonsCount: 4,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: 'luk1-stats',
    course: 'Planner',
    person: 'luk2',
    email: 'lukeon2+2@gmail.com',
    department: '',
    location: '',
    courseStartedDate: '',
    openedLessonsCount: '0',
    completedDate: '',
    completedLessonsCount: 0,
    totalLessonsCount: 3,
    haveNotStarted: '1',
    notOnSchedule: '1',
    haveStarted: '0',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: 'mailing1-6:30',
    course: 'test - copy',
    person: 'luk2',
    email: 'lukeon2+2@gmail.com',
    department: '',
    location: '',
    courseStartedDate: '',
    openedLessonsCount: '0',
    completedDate: '',
    completedLessonsCount: 0,
    totalLessonsCount: 1,
    haveNotStarted: '1',
    notOnSchedule: '1',
    haveStarted: '0',
    quizScore: 0,
    quizScoreTotal: 1,
    certificateTitle: null,
  },
  {
    project: 'mailing1-6:30',
    course: 'test - copy',
    person: 'Lukasz',
    email: 'lukasz@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2021-04-14 14:50:04',
    openedLessonsCount: '3',
    completedDate: '2021-04-14 14:50:57',
    completedLessonsCount: 3,
    totalLessonsCount: 3,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 1,
    quizScoreTotal: 1,
    certificateTitle: null,
  },
  {
    project: 'mailsfn1',
    course: 'Demo for Lukasz Coding',
    person: 'Lukasz',
    email: 'lukasz@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2019-06-19 14:11:11',
    openedLessonsCount: '3',
    completedDate: '2020-03-02 02:38:57',
    completedLessonsCount: 3,
    totalLessonsCount: 3,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 1,
    certificateTitle: null,
  },
  {
    project: 'mailsfn1',
    course: 'Demo for Lukasz Coding',
    person: 'Lukasz',
    email: 'l.jarmulowicz@gmail.com',
    department: '',
    location: '',
    courseStartedDate: '',
    openedLessonsCount: '0',
    completedDate: '',
    completedLessonsCount: 0,
    totalLessonsCount: 3,
    haveNotStarted: '1',
    notOnSchedule: '1',
    haveStarted: '0',
    quizScore: 0,
    quizScoreTotal: 1,
    certificateTitle: null,
  },
  {
    project: 'mapping1-test04122019',
    course: 'Kom i gang med SharePoint Online',
    person: 'Lukasz',
    email: 'lukasz@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2020-06-25 09:24:52',
    openedLessonsCount: '1',
    completedDate: '',
    completedLessonsCount: 0,
    totalLessonsCount: 3,
    haveNotStarted: '0',
    notOnSchedule: '1',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Arbeidsmiljø er mer enn verneutstyr ',
    person: 'luk2',
    email: 'lukeon2+2@gmail.com',
    department: '',
    location: '',
    courseStartedDate: '2019-11-20 07:52:59',
    openedLessonsCount: '4',
    completedDate: '2019-11-20 07:53:46',
    completedLessonsCount: 4,
    totalLessonsCount: 4,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Arbeidsmiljø er mer enn verneutstyr ',
    person: 'Lukasz',
    email: 'lukasz@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2020-01-17 12:41:34',
    openedLessonsCount: '2',
    completedDate: '',
    completedLessonsCount: 0,
    totalLessonsCount: 4,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Decisions - Møteansvarlig',
    person: 'Anonymous user',
    email: '',
    department: '',
    location: '',
    courseStartedDate: '2020-03-04 07:52:10',
    openedLessonsCount: '61',
    completedDate: 'N/A',
    completedLessonsCount: 10,
    totalLessonsCount: 400,
    haveNotStarted: 'N/A',
    notOnSchedule: 'N/A',
    haveStarted: 'N/A',
    quizScore: 1,
    quizScoreTotal: 250,
    certificateTitle: 'N/A',
  },
  {
    project: 'Self Service',
    course: 'Decisions - Møteansvarlig',
    person: 'luk2',
    email: 'lukeon2+2@gmail.com',
    department: '',
    location: '',
    courseStartedDate: '2021-04-14 15:01:43',
    openedLessonsCount: '1',
    completedDate: '',
    completedLessonsCount: 0,
    totalLessonsCount: 8,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 5,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Decisions - Møteansvarlig',
    person: 'Lukasz',
    email: 'lukasz@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2020-03-03 11:59:59',
    openedLessonsCount: '7',
    completedDate: '',
    completedLessonsCount: 6,
    totalLessonsCount: 8,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 4,
    quizScoreTotal: 5,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Decisions - Møteansvarlig',
    person: 'Pawel',
    email: 'pawel@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2020-03-19 10:52:17',
    openedLessonsCount: '4',
    completedDate: '',
    completedLessonsCount: 2,
    totalLessonsCount: 8,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 5,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Decisions - Møteansvarlig',
    person: 'webmaster',
    email: 'webmaster@silesiacode.com',
    department: 'Opplæring',
    location: 'Oslo',
    courseStartedDate: '2020-03-03 12:00:13',
    openedLessonsCount: '4',
    completedDate: '',
    completedLessonsCount: 3,
    totalLessonsCount: 8,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 5,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Demo for Lukasz Coding',
    person: 'Anonymous user',
    email: '',
    department: '',
    location: '',
    courseStartedDate: '2020-01-14 11:23:41',
    openedLessonsCount: '19',
    completedDate: 'N/A',
    completedLessonsCount: 3,
    totalLessonsCount: 33,
    haveNotStarted: 'N/A',
    notOnSchedule: 'N/A',
    haveStarted: 'N/A',
    quizScore: 1,
    quizScoreTotal: 11,
    certificateTitle: 'N/A',
  },
  {
    project: 'Self Service',
    course: 'Demo for Lukasz Coding',
    person: 'Lukasz',
    email: 'lukasz@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2019-06-19 13:53:10',
    openedLessonsCount: '1',
    completedDate: '',
    completedLessonsCount: 0,
    totalLessonsCount: 3,
    haveNotStarted: '0',
    notOnSchedule: '1',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 1,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Demo for Lukasz Coding',
    person: 'Pawel',
    email: 'pawel@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2020-03-20 00:08:50',
    openedLessonsCount: '1',
    completedDate: '',
    completedLessonsCount: 0,
    totalLessonsCount: 3,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 1,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Demo for Lukasz Coding',
    person: 'webmaster',
    email: 'webmaster@silesiacode.com',
    department: 'Opplæring',
    location: 'Oslo',
    courseStartedDate: '2020-03-02 13:23:19',
    openedLessonsCount: '1',
    completedDate: '',
    completedLessonsCount: 1,
    totalLessonsCount: 3,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 1,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Dokumentbibliotek i SharePoint Online',
    person: 'Anonymous user',
    email: '',
    department: '',
    location: '',
    courseStartedDate: '2019-07-05 07:33:51',
    openedLessonsCount: '15',
    completedDate: 'N/A',
    completedLessonsCount: 3,
    totalLessonsCount: 96,
    haveNotStarted: 'N/A',
    notOnSchedule: 'N/A',
    haveStarted: 'N/A',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: 'N/A',
  },
  {
    project: 'Self Service',
    course: 'Dokumentbibliotek i SharePoint Online',
    person: 'Lukasz',
    email: 'lukasz@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2020-01-13 10:22:47',
    openedLessonsCount: '6',
    completedDate: '',
    completedLessonsCount: 0,
    totalLessonsCount: 8,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Dokumentbibliotek i SharePoint Online',
    person: 'Pawel',
    email: 'pawel@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2019-04-09 13:09:21',
    openedLessonsCount: '2',
    completedDate: '',
    completedLessonsCount: 0,
    totalLessonsCount: 8,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Dokumentbibliotek i SharePoint Online',
    person: 'webmaster',
    email: 'webmaster@silesiacode.com',
    department: 'Opplæring',
    location: 'Oslo',
    courseStartedDate: '2020-03-02 15:24:56',
    openedLessonsCount: '1',
    completedDate: '',
    completedLessonsCount: 1,
    totalLessonsCount: 8,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'evaluation',
    person: 'Anonymous user',
    email: '',
    department: '',
    location: '',
    courseStartedDate: '2021-03-09 09:34:57',
    openedLessonsCount: '4',
    completedDate: 'N/A',
    completedLessonsCount: 4,
    totalLessonsCount: 4,
    haveNotStarted: 'N/A',
    notOnSchedule: 'N/A',
    haveStarted: 'N/A',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: 'N/A',
  },
  {
    project: 'Self Service',
    course: 'evaluation',
    person: 'Jøraholmen, Per Martin',
    email: 'per.martin.joraholmen@innlandetfylke.no',
    department: '',
    location: '',
    courseStartedDate: '2021-03-09 09:38:23',
    openedLessonsCount: '1',
    completedDate: '2021-03-09 09:38:44',
    completedLessonsCount: 1,
    totalLessonsCount: 1,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Excel 2016',
    person: 'Anonymous user',
    email: '',
    department: '',
    location: '',
    courseStartedDate: '2019-12-20 14:13:30',
    openedLessonsCount: '9',
    completedDate: 'N/A',
    completedLessonsCount: 0,
    totalLessonsCount: 160,
    haveNotStarted: 'N/A',
    notOnSchedule: 'N/A',
    haveStarted: 'N/A',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: 'N/A',
  },
  {
    project: 'Self Service',
    course: 'Excel 2016',
    person: 'Lukasz',
    email: 'lukasz@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2020-01-15 12:56:58',
    openedLessonsCount: '4',
    completedDate: '',
    completedLessonsCount: 0,
    totalLessonsCount: 20,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Extreme quizes',
    person: 'Anonymous user',
    email: '',
    department: '',
    location: '',
    courseStartedDate: '2020-04-10 00:04:08',
    openedLessonsCount: '11',
    completedDate: 'N/A',
    completedLessonsCount: 0,
    totalLessonsCount: 11,
    haveNotStarted: 'N/A',
    notOnSchedule: 'N/A',
    haveStarted: 'N/A',
    quizScore: 0,
    quizScoreTotal: 33,
    certificateTitle: 'N/A',
  },
  {
    project: 'Self Service',
    course: 'Extreme quizes',
    person: 'Pawel',
    email: 'pawel@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '',
    openedLessonsCount: '0',
    completedDate: '',
    completedLessonsCount: 0,
    totalLessonsCount: 1,
    haveNotStarted: '1',
    notOnSchedule: '0',
    haveStarted: '0',
    quizScore: 0,
    quizScoreTotal: 3,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Extreme quizes',
    person: 'Pawel',
    email: 'pawel@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2020-04-08 16:06:37',
    openedLessonsCount: '1',
    completedDate: '',
    completedLessonsCount: 0,
    totalLessonsCount: 1,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 3,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'GDPR - Hvorfor, hvordan og hva',
    person: 'Anonymous user',
    email: '',
    department: '',
    location: '',
    courseStartedDate: '2019-11-26 15:32:05',
    openedLessonsCount: '3',
    completedDate: 'N/A',
    completedLessonsCount: 0,
    totalLessonsCount: 21,
    haveNotStarted: 'N/A',
    notOnSchedule: 'N/A',
    haveStarted: 'N/A',
    quizScore: 0,
    quizScoreTotal: 21,
    certificateTitle: 'N/A',
  },
  {
    project: 'Self Service',
    course: 'GDPR - Hvorfor, hvordan og hva',
    person: 'Lukasz',
    email: 'lukasz@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2019-12-20 15:07:57',
    openedLessonsCount: '5',
    completedDate: '',
    completedLessonsCount: 0,
    totalLessonsCount: 7,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 7,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Hva kan du forvente?',
    person: 'Lukasz',
    email: 'l.jarmulowicz@gmail.com',
    department: '',
    location: '',
    courseStartedDate: '2019-03-14 08:26:50',
    openedLessonsCount: '1',
    completedDate: '',
    completedLessonsCount: 1,
    totalLessonsCount: 3,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Hva kan du forvente?',
    person: 'Lukasz',
    email: 'lukasz@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2020-09-03 10:24:40',
    openedLessonsCount: '2',
    completedDate: '',
    completedLessonsCount: 0,
    totalLessonsCount: 3,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Hvorfor er HMS viktig for meg?',
    person: 'Anonymous user',
    email: '',
    department: '',
    location: '',
    courseStartedDate: '2020-03-07 19:29:20',
    openedLessonsCount: '18',
    completedDate: 'N/A',
    completedLessonsCount: 4,
    totalLessonsCount: 120,
    haveNotStarted: 'N/A',
    notOnSchedule: 'N/A',
    haveStarted: 'N/A',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: 'N/A',
  },
  {
    project: 'Self Service',
    course: 'Hvorfor er HMS viktig for meg?',
    person: 'Lukasz',
    email: 'lukasz@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2020-03-07 19:21:58',
    openedLessonsCount: '7',
    completedDate: '',
    completedLessonsCount: 6,
    totalLessonsCount: 8,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Kom i gang med Dynamics CRM ',
    person: 'Anonymous user',
    email: '',
    department: '',
    location: '',
    courseStartedDate: '2020-02-28 16:36:22',
    openedLessonsCount: '1',
    completedDate: 'N/A',
    completedLessonsCount: 0,
    totalLessonsCount: 7,
    haveNotStarted: 'N/A',
    notOnSchedule: 'N/A',
    haveStarted: 'N/A',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: 'N/A',
  },
  {
    project: 'Self Service',
    course: 'Kom i gang med SharePoint Online',
    person: 'Anonymous user',
    email: '',
    department: '',
    location: '',
    courseStartedDate: '2019-08-23 09:30:17',
    openedLessonsCount: '11',
    completedDate: 'N/A',
    completedLessonsCount: 4,
    totalLessonsCount: 30,
    haveNotStarted: 'N/A',
    notOnSchedule: 'N/A',
    haveStarted: 'N/A',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: 'N/A',
  },
  {
    project: 'Self Service',
    course: 'Kom i gang med SharePoint Online',
    person: 'Lukasz',
    email: 'lukasz@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2019-07-03 06:16:58',
    openedLessonsCount: '3',
    completedDate: '',
    completedLessonsCount: 0,
    totalLessonsCount: 3,
    haveNotStarted: '0',
    notOnSchedule: '1',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Kom i gang med SharePoint Online',
    person: 'Lukasz',
    email: 'l.jarmulowicz@gmail.com',
    department: '',
    location: '',
    courseStartedDate: '2019-03-21 10:37:17',
    openedLessonsCount: '1',
    completedDate: '',
    completedLessonsCount: 0,
    totalLessonsCount: 3,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Kom i gang med SharePoint Online',
    person: 'Pawel',
    email: 'pawel@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2020-04-21 09:20:00',
    openedLessonsCount: '2',
    completedDate: '',
    completedLessonsCount: 0,
    totalLessonsCount: 3,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Kom i gang med SharePoint Online',
    person: 'webmaster',
    email: 'webmaster@silesiacode.com',
    department: 'Opplæring',
    location: 'Oslo',
    courseStartedDate: '2020-03-02 15:25:17',
    openedLessonsCount: '1',
    completedDate: '',
    completedLessonsCount: 1,
    totalLessonsCount: 3,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Kundeservice i Dynamics CRM',
    person: 'Anonymous user',
    email: '',
    department: '',
    location: '',
    courseStartedDate: '2021-04-16 11:19:49',
    openedLessonsCount: '1',
    completedDate: 'N/A',
    completedLessonsCount: 1,
    totalLessonsCount: 9,
    haveNotStarted: 'N/A',
    notOnSchedule: 'N/A',
    haveStarted: 'N/A',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: 'N/A',
  },
  {
    project: 'Self Service',
    course: 'Kundeservice i Dynamics CRM',
    person: 'luk2',
    email: 'lukeon2+2@gmail.com',
    department: '',
    location: '',
    courseStartedDate: '2020-04-28 08:35:03',
    openedLessonsCount: '2',
    completedDate: '',
    completedLessonsCount: 0,
    totalLessonsCount: 9,
    haveNotStarted: '0',
    notOnSchedule: '1',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Lag og del dokumenter i SharePoint',
    person: 'Anonymous user',
    email: '',
    department: '',
    location: '',
    courseStartedDate: '2019-07-03 12:16:15',
    openedLessonsCount: '9',
    completedDate: 'N/A',
    completedLessonsCount: 3,
    totalLessonsCount: 36,
    haveNotStarted: 'N/A',
    notOnSchedule: 'N/A',
    haveStarted: 'N/A',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: 'N/A',
  },
  {
    project: 'Self Service',
    course: 'Lag og del dokumenter i SharePoint',
    person: 'Lukasz',
    email: 'lukasz@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2020-03-04 09:42:23',
    openedLessonsCount: '1',
    completedDate: '',
    completedLessonsCount: 0,
    totalLessonsCount: 6,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Lag og del dokumenter i SharePoint',
    person: 'Pawel',
    email: 'pawel@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2019-10-31 11:58:50',
    openedLessonsCount: '1',
    completedDate: '',
    completedLessonsCount: 0,
    totalLessonsCount: 6,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Lovpålagt lønnsomhet',
    person: 'Anonymous user',
    email: '',
    department: '',
    location: '',
    courseStartedDate: '2019-11-15 15:08:33',
    openedLessonsCount: '3',
    completedDate: 'N/A',
    completedLessonsCount: 0,
    totalLessonsCount: 6,
    haveNotStarted: 'N/A',
    notOnSchedule: 'N/A',
    haveStarted: 'N/A',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: 'N/A',
  },
  {
    project: 'Self Service',
    course: 'Lovpålagt lønnsomhet',
    person: 'Lukasz',
    email: 'lukasz@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2020-01-17 12:38:56',
    openedLessonsCount: '2',
    completedDate: '',
    completedLessonsCount: 0,
    totalLessonsCount: 3,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Markedsføring i Dynamics CRM',
    person: 'Anonymous user',
    email: '',
    department: '',
    location: '',
    courseStartedDate: '2020-02-28 16:36:34',
    openedLessonsCount: '1',
    completedDate: 'N/A',
    completedLessonsCount: 0,
    totalLessonsCount: 4,
    haveNotStarted: 'N/A',
    notOnSchedule: 'N/A',
    haveStarted: 'N/A',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: 'N/A',
  },
  {
    project: 'Self Service',
    course: 'Markedsføring i Dynamics CRM',
    person: 'Lukasz',
    email: 'lukasz@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2020-02-28 16:35:55',
    openedLessonsCount: '1',
    completedDate: '',
    completedLessonsCount: 0,
    totalLessonsCount: 4,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Markedsføring i Dynamics CRM',
    person: 'Pawel',
    email: 'pawel@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2019-04-01 12:37:14',
    openedLessonsCount: '1',
    completedDate: '',
    completedLessonsCount: 1,
    totalLessonsCount: 4,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'MS Office 2016',
    person: 'Anonymous user',
    email: '',
    department: '',
    location: '',
    courseStartedDate: '2021-04-16 23:21:50',
    openedLessonsCount: '2',
    completedDate: 'N/A',
    completedLessonsCount: 2,
    totalLessonsCount: 12,
    haveNotStarted: 'N/A',
    notOnSchedule: 'N/A',
    haveStarted: 'N/A',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: 'N/A',
  },
  {
    project: 'Self Service',
    course: 'MS Office 2016',
    person: 'Lukasz',
    email: 'lukasz@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2019-07-30 13:23:18',
    openedLessonsCount: '1',
    completedDate: '',
    completedLessonsCount: 0,
    totalLessonsCount: 12,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'MS Project',
    person: 'Anonymous user',
    email: '',
    department: '',
    location: '',
    courseStartedDate: '2019-10-04 06:02:21',
    openedLessonsCount: '2',
    completedDate: 'N/A',
    completedLessonsCount: 1,
    totalLessonsCount: 22,
    haveNotStarted: 'N/A',
    notOnSchedule: 'N/A',
    haveStarted: 'N/A',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: 'N/A',
  },
  {
    project: 'Self Service',
    course: 'MS Project',
    person: 'Lukasz',
    email: 'lukasz@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2020-07-13 13:39:07',
    openedLessonsCount: '1',
    completedDate: '',
    completedLessonsCount: 0,
    totalLessonsCount: 22,
    haveNotStarted: '0',
    notOnSchedule: '1',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'New course - Extereme Slides CSS Fixes',
    person: 'Anonymous user',
    email: '',
    department: '',
    location: '',
    courseStartedDate: '2020-01-13 10:04:18',
    openedLessonsCount: '168',
    completedDate: 'N/A',
    completedLessonsCount: 55,
    totalLessonsCount: 4710,
    haveNotStarted: 'N/A',
    notOnSchedule: 'N/A',
    haveStarted: 'N/A',
    quizScore: 131,
    quizScoreTotal: 27161,
    certificateTitle: 'N/A',
  },
  {
    project: 'Self Service',
    course: 'New course - Extereme Slides CSS Fixes',
    person: 'Lukasz',
    email: 'lukasz@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2019-12-17 09:04:46',
    openedLessonsCount: '2',
    completedDate: '2020-04-23 21:18:13',
    completedLessonsCount: 2,
    totalLessonsCount: 2,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 7,
    quizScoreTotal: 12,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'New course - Extereme Slides CSS Fixes',
    person: 'Marcin Pec',
    email: 'marcin.pec@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2021-03-29 11:42:27',
    openedLessonsCount: '1',
    completedDate: '',
    completedLessonsCount: 1,
    totalLessonsCount: 30,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 1,
    quizScoreTotal: 170,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'New course - Extereme Slides CSS Fixes',
    person: 'Pawel',
    email: 'pawel@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2020-03-20 01:02:02',
    openedLessonsCount: '26',
    completedDate: '',
    completedLessonsCount: 20,
    totalLessonsCount: 27,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 35,
    quizScoreTotal: 149,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'New course - Extereme Slides CSS Fixes',
    person: 'user1',
    email: 'xm-user45@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2020-10-22 16:31:27',
    openedLessonsCount: '2',
    completedDate: '',
    completedLessonsCount: 0,
    totalLessonsCount: 30,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 170,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'New course - Extereme Slides CSS Fixes',
    person: 'webmaster',
    email: 'webmaster@silesiacode.com',
    department: 'Opplæring',
    location: 'Oslo',
    courseStartedDate: '2020-02-26 15:39:06',
    openedLessonsCount: '4',
    completedDate: '2020-04-21 17:07:39',
    completedLessonsCount: 4,
    totalLessonsCount: 4,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 1,
    quizScoreTotal: 24,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Nyheter i Office 2016',
    person: 'Anonymous user',
    email: '',
    department: '',
    location: '',
    courseStartedDate: '2019-12-18 16:06:38',
    openedLessonsCount: '1',
    completedDate: 'N/A',
    completedLessonsCount: 0,
    totalLessonsCount: 12,
    haveNotStarted: 'N/A',
    notOnSchedule: 'N/A',
    haveStarted: 'N/A',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: 'N/A',
  },
  {
    project: 'Self Service',
    course: 'Office 365',
    person: 'Anonymous user',
    email: '',
    department: '',
    location: '',
    courseStartedDate: '2019-11-06 13:10:23',
    openedLessonsCount: '8',
    completedDate: 'N/A',
    completedLessonsCount: 2,
    totalLessonsCount: 63,
    haveNotStarted: 'N/A',
    notOnSchedule: 'N/A',
    haveStarted: 'N/A',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: 'N/A',
  },
  {
    project: 'Self Service',
    course: 'Office 365',
    person: 'Lukasz',
    email: 'lukasz@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2019-11-06 12:21:57',
    openedLessonsCount: '3',
    completedDate: '',
    completedLessonsCount: 1,
    totalLessonsCount: 9,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Office 365',
    person: 'Pawel',
    email: 'pawel@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2019-04-01 12:23:10',
    openedLessonsCount: '7',
    completedDate: '',
    completedLessonsCount: 6,
    totalLessonsCount: 9,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Office 365',
    person: 'user1',
    email: 'xm-user45@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2021-01-05 16:27:23',
    openedLessonsCount: '1',
    completedDate: '',
    completedLessonsCount: 0,
    totalLessonsCount: 9,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Opplæringspakken 2019',
    person: 'Anonymous user',
    email: '',
    department: '',
    location: '',
    courseStartedDate: '2020-02-28 12:11:32',
    openedLessonsCount: '202',
    completedDate: 'N/A',
    completedLessonsCount: 87,
    totalLessonsCount: 1504,
    haveNotStarted: 'N/A',
    notOnSchedule: 'N/A',
    haveStarted: 'N/A',
    quizScore: 129,
    quizScoreTotal: 1316,
    certificateTitle: 'N/A',
  },
  {
    project: 'Self Service',
    course: 'Opplæringspakken 2019',
    person: 'Lukasz',
    email: 'lukasz@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2020-02-28 12:11:03',
    openedLessonsCount: '8',
    completedDate: '2021-05-12 14:43:06',
    completedLessonsCount: 8,
    totalLessonsCount: 8,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 2,
    quizScoreTotal: 7,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Opplæringspakken 2019',
    person: 'Pawel',
    email: 'pawel@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2020-04-02 15:43:35',
    openedLessonsCount: '1',
    completedDate: '',
    completedLessonsCount: 1,
    totalLessonsCount: 8,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 2,
    quizScoreTotal: 7,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Opplæringspakken 2019',
    person: 'webmaster',
    email: 'webmaster@silesiacode.com',
    department: 'Opplæring',
    location: 'Oslo',
    courseStartedDate: '2020-03-02 15:21:38',
    openedLessonsCount: '8',
    completedDate: '',
    completedLessonsCount: 7,
    totalLessonsCount: 8,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 7,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Oppnå mer med Outlook 2016',
    person: 'Lukasz',
    email: 'lukasz@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2020-01-17 12:40:09',
    openedLessonsCount: '2',
    completedDate: '',
    completedLessonsCount: 0,
    totalLessonsCount: 14,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Planner',
    person: 'Anonymous user',
    email: '',
    department: '',
    location: '',
    courseStartedDate: '2019-10-15 00:58:13',
    openedLessonsCount: '4',
    completedDate: 'N/A',
    completedLessonsCount: 0,
    totalLessonsCount: 3,
    haveNotStarted: 'N/A',
    notOnSchedule: 'N/A',
    haveStarted: 'N/A',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: 'N/A',
  },
  {
    project: 'Self Service',
    course: 'Planner',
    person: 'Lukasz',
    email: 'lukasz@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2019-04-15 06:28:00',
    openedLessonsCount: '3',
    completedDate: '2019-11-20 07:19:46',
    completedLessonsCount: 3,
    totalLessonsCount: 3,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Planner',
    person: 'Pawel',
    email: 'pawel@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2019-04-01 12:25:22',
    openedLessonsCount: '3',
    completedDate: '2019-04-02 16:05:53',
    completedLessonsCount: 3,
    totalLessonsCount: 3,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Quiz deploy test April',
    person: 'Anonymous user',
    email: '',
    department: '',
    location: '',
    courseStartedDate: '2020-04-23 09:09:57',
    openedLessonsCount: '14',
    completedDate: 'N/A',
    completedLessonsCount: 11,
    totalLessonsCount: 42,
    haveNotStarted: 'N/A',
    notOnSchedule: 'N/A',
    haveStarted: 'N/A',
    quizScore: 9,
    quizScoreTotal: 84,
    certificateTitle: 'N/A',
  },
  {
    project: 'Self Service',
    course: 'Quiz deploy test April',
    person: 'Pawel',
    email: 'pawel@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2020-04-23 09:16:11',
    openedLessonsCount: '3',
    completedDate: '2020-04-23 17:13:29',
    completedLessonsCount: 3,
    totalLessonsCount: 3,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 2,
    quizScoreTotal: 6,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Quizes',
    person: 'Anonymous user',
    email: '',
    department: '',
    location: '',
    courseStartedDate: '2020-03-07 12:59:49',
    openedLessonsCount: '30',
    completedDate: 'N/A',
    completedLessonsCount: 4,
    totalLessonsCount: 112,
    haveNotStarted: 'N/A',
    notOnSchedule: 'N/A',
    haveStarted: 'N/A',
    quizScore: 7,
    quizScoreTotal: 140,
    certificateTitle: 'N/A',
  },
  {
    project: 'Self Service',
    course: 'Quizes',
    person: 'Lukasz',
    email: 'lukasz@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2020-03-05 09:17:47',
    openedLessonsCount: '4',
    completedDate: '2021-05-12 14:42:09',
    completedLessonsCount: 4,
    totalLessonsCount: 4,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 2,
    quizScoreTotal: 5,
    certificateTitle: 'lukas quiz',
  },
  {
    project: 'Self Service',
    course: 'Quizes',
    person: 'Pawel',
    email: 'pawel@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2020-04-08 01:26:59',
    openedLessonsCount: '3',
    completedDate: '',
    completedLessonsCount: 1,
    totalLessonsCount: 4,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 1,
    quizScoreTotal: 5,
    certificateTitle: 'lukas quiz',
  },
  {
    project: 'Self Service',
    course: 'Quizes',
    person: 'webmaster',
    email: 'webmaster@silesiacode.com',
    department: 'Opplæring',
    location: 'Oslo',
    courseStartedDate: '2020-03-06 10:48:05',
    openedLessonsCount: '2',
    completedDate: '',
    completedLessonsCount: 2,
    totalLessonsCount: 4,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 5,
    certificateTitle: 'lukas quiz',
  },
  {
    project: 'Self Service',
    course: 'Rapportering og analyse i Dynamics CRM',
    person: 'Lukasz',
    email: 'lukasz@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2020-03-06 19:19:03',
    openedLessonsCount: '2',
    completedDate: '',
    completedLessonsCount: 0,
    totalLessonsCount: 6,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Salg i Dynamics CRM',
    person: 'Lukasz',
    email: 'lukasz@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2020-07-13 12:43:28',
    openedLessonsCount: '1',
    completedDate: '',
    completedLessonsCount: 0,
    totalLessonsCount: 7,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Service scheduling i Dynamics CRM',
    person: 'Lukasz',
    email: 'lukasz@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2020-07-21 09:53:08',
    openedLessonsCount: '1',
    completedDate: '',
    completedLessonsCount: 0,
    totalLessonsCount: 10,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 1,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Sikkerhet 2019 - XtraMile Videokurs',
    person: 'Anonymous user',
    email: '',
    department: '',
    location: '',
    courseStartedDate: '2020-03-09 06:03:27',
    openedLessonsCount: '6',
    completedDate: 'N/A',
    completedLessonsCount: 1,
    totalLessonsCount: 35,
    haveNotStarted: 'N/A',
    notOnSchedule: 'N/A',
    haveStarted: 'N/A',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: 'N/A',
  },
  {
    project: 'Self Service',
    course: 'Sikkerhet 2019 - XtraMile Videokurs',
    person: 'Lukasz',
    email: 'lukasz@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2020-03-07 19:22:43',
    openedLessonsCount: '2',
    completedDate: '',
    completedLessonsCount: 1,
    totalLessonsCount: 7,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Sikkerhet 2019 - XtraMile Videokurs',
    person: 'user1',
    email: 'xm-user45@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '',
    openedLessonsCount: '0',
    completedDate: '',
    completedLessonsCount: 0,
    totalLessonsCount: 7,
    haveNotStarted: '1',
    notOnSchedule: '1',
    haveStarted: '0',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Skype for Business',
    person: 'Anonymous user',
    email: '',
    department: '',
    location: '',
    courseStartedDate: '2019-10-15 07:27:02',
    openedLessonsCount: '19',
    completedDate: 'N/A',
    completedLessonsCount: 3,
    totalLessonsCount: 154,
    haveNotStarted: 'N/A',
    notOnSchedule: 'N/A',
    haveStarted: 'N/A',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: 'N/A',
  },
  {
    project: 'Self Service',
    course: 'Skype for Business',
    person: 'Lukasz',
    email: 'lukasz@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2020-01-14 13:47:40',
    openedLessonsCount: '2',
    completedDate: '',
    completedLessonsCount: 1,
    totalLessonsCount: 11,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Skype for Business',
    person: 'Pawel',
    email: 'pawel@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2020-03-20 10:15:03',
    openedLessonsCount: '1',
    completedDate: '',
    completedLessonsCount: 0,
    totalLessonsCount: 11,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Skype for Business',
    person: 'webmaster',
    email: 'webmaster@silesiacode.com',
    department: 'Opplæring',
    location: 'Oslo',
    courseStartedDate: '2020-03-02 13:16:28',
    openedLessonsCount: '1',
    completedDate: '',
    completedLessonsCount: 1,
    totalLessonsCount: 11,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Søk og deling av innhold i SharePoint',
    person: 'Anonymous user',
    email: '',
    department: '',
    location: '',
    courseStartedDate: '2019-08-26 11:20:58',
    openedLessonsCount: '4',
    completedDate: 'N/A',
    completedLessonsCount: 1,
    totalLessonsCount: 15,
    haveNotStarted: 'N/A',
    notOnSchedule: 'N/A',
    haveStarted: 'N/A',
    quizScore: 0,
    quizScoreTotal: 6,
    certificateTitle: 'N/A',
  },
  {
    project: 'Self Service',
    course: 'Søk og deling av innhold i SharePoint',
    person: 'Lukasz',
    email: 'l.jarmulowicz@gmail.com',
    department: '',
    location: '',
    courseStartedDate: '2019-11-20 08:03:42',
    openedLessonsCount: '4',
    completedDate: '2019-11-20 08:07:07',
    completedLessonsCount: 4,
    totalLessonsCount: 4,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 1,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Søk og deling av innhold i SharePoint',
    person: 'Lukasz',
    email: 'lukasz@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2020-01-17 09:40:43',
    openedLessonsCount: '2',
    completedDate: '',
    completedLessonsCount: 0,
    totalLessonsCount: 4,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 1,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Sway',
    person: 'Anonymous user',
    email: '',
    department: '',
    location: '',
    courseStartedDate: '2019-12-09 11:59:17',
    openedLessonsCount: '1',
    completedDate: 'N/A',
    completedLessonsCount: 0,
    totalLessonsCount: 4,
    haveNotStarted: 'N/A',
    notOnSchedule: 'N/A',
    haveStarted: 'N/A',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: 'N/A',
  },
  {
    project: 'Self Service',
    course: 'Sway',
    person: 'Lukasz',
    email: 'lukasz@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2019-09-12 09:28:17',
    openedLessonsCount: '2',
    completedDate: '',
    completedLessonsCount: 2,
    totalLessonsCount: 4,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Teams - Administrer medlemmer og innhold',
    person: 'Anonymous user',
    email: '',
    department: '',
    location: '',
    courseStartedDate: '2019-10-24 04:04:50',
    openedLessonsCount: '2',
    completedDate: 'N/A',
    completedLessonsCount: 0,
    totalLessonsCount: 8,
    haveNotStarted: 'N/A',
    notOnSchedule: 'N/A',
    haveStarted: 'N/A',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: 'N/A',
  },
  {
    project: 'Self Service',
    course: 'Teams - Administrer medlemmer og innhold',
    person: 'Lukasz',
    email: 'lukasz@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2020-01-17 08:44:04',
    openedLessonsCount: '3',
    completedDate: '',
    completedLessonsCount: 0,
    totalLessonsCount: 4,
    haveNotStarted: '0',
    notOnSchedule: '1',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Teams - Administrer medlemmer og innhold',
    person: 'webmaster',
    email: 'webmaster@silesiacode.com',
    department: 'Opplæring',
    location: 'Oslo',
    courseStartedDate: '2020-03-12 16:32:50',
    openedLessonsCount: '1',
    completedDate: '',
    completedLessonsCount: 0,
    totalLessonsCount: 4,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Teams - Effektiv Samhandling',
    person: 'Anonymous user',
    email: '',
    department: '',
    location: '',
    courseStartedDate: '2020-03-07 19:29:09',
    openedLessonsCount: '40',
    completedDate: 'N/A',
    completedLessonsCount: 9,
    totalLessonsCount: 340,
    haveNotStarted: 'N/A',
    notOnSchedule: 'N/A',
    haveStarted: 'N/A',
    quizScore: 0,
    quizScoreTotal: 34,
    certificateTitle: 'N/A',
  },
  {
    project: 'Self Service',
    course: 'Teams - Effektiv Samhandling',
    person: 'Lukasz',
    email: 'lukasz@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2020-03-07 19:22:58',
    openedLessonsCount: '6',
    completedDate: '',
    completedLessonsCount: 5,
    totalLessonsCount: 9,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 1,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Teams - Effektiv Samhandling',
    person: 'Pawel',
    email: 'pawel@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2020-03-27 11:51:50',
    openedLessonsCount: '1',
    completedDate: '',
    completedLessonsCount: 0,
    totalLessonsCount: 9,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 1,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Teams - Effektive møter',
    person: 'Anonymous user',
    email: '',
    department: '',
    location: '',
    courseStartedDate: '2020-03-08 09:21:27',
    openedLessonsCount: '10',
    completedDate: 'N/A',
    completedLessonsCount: 2,
    totalLessonsCount: 45,
    haveNotStarted: 'N/A',
    notOnSchedule: 'N/A',
    haveStarted: 'N/A',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: 'N/A',
  },
  {
    project: 'Self Service',
    course: 'Teams - Effektive møter',
    person: 'Lukasz',
    email: 'lukasz@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2020-03-07 19:35:56',
    openedLessonsCount: '2',
    completedDate: '',
    completedLessonsCount: 1,
    totalLessonsCount: 5,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Teams - Effektive møter',
    person: 'webmaster',
    email: 'webmaster@silesiacode.com',
    department: 'Opplæring',
    location: 'Oslo',
    courseStartedDate: '2020-03-17 13:01:15',
    openedLessonsCount: '1',
    completedDate: '',
    completedLessonsCount: 1,
    totalLessonsCount: 5,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Teams - Gjør samhandling enklere',
    person: 'Anonymous user',
    email: '',
    department: '',
    location: '',
    courseStartedDate: '2019-10-03 21:45:12',
    openedLessonsCount: '5',
    completedDate: 'N/A',
    completedLessonsCount: 0,
    totalLessonsCount: 5,
    haveNotStarted: 'N/A',
    notOnSchedule: 'N/A',
    haveStarted: 'N/A',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: 'N/A',
  },
  {
    project: 'Self Service',
    course: 'Teams - Gjør samhandling enklere',
    person: 'Lukasz',
    email: 'lukasz@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2019-12-09 10:03:02',
    openedLessonsCount: '3',
    completedDate: '',
    completedLessonsCount: 0,
    totalLessonsCount: 4,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Teams - Kom i gang med Microsoft Teams',
    person: 'Anonymous user',
    email: '',
    department: '',
    location: '',
    courseStartedDate: '2019-10-01 10:24:56',
    openedLessonsCount: '6',
    completedDate: 'N/A',
    completedLessonsCount: 0,
    totalLessonsCount: 9,
    haveNotStarted: 'N/A',
    notOnSchedule: 'N/A',
    haveStarted: 'N/A',
    quizScore: 0,
    quizScoreTotal: 3,
    certificateTitle: 'N/A',
  },
  {
    project: 'Self Service',
    course: 'Teams - Kom i gang med Microsoft Teams',
    person: 'Lukasz',
    email: 'l.jarmulowicz@gmail.com',
    department: '',
    location: '',
    courseStartedDate: '2020-09-16 20:06:44',
    openedLessonsCount: '3',
    completedDate: '2020-09-16 20:11:24',
    completedLessonsCount: 3,
    totalLessonsCount: 3,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 1,
    certificateTitle: 'lukkaaatest',
  },
  {
    project: 'Self Service',
    course: 'Teams - Kom i gang med Microsoft Teams',
    person: 'Lukasz',
    email: 'lukasz@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2019-07-30 13:07:00',
    openedLessonsCount: '3',
    completedDate: '2020-09-16 19:57:58',
    completedLessonsCount: 3,
    totalLessonsCount: 3,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 1,
    certificateTitle: 'lukkaaatest',
  },
  {
    project: 'Self Service',
    course: 'test - copy',
    person: 'Anonymous user',
    email: '',
    department: '',
    location: '',
    courseStartedDate: '2020-09-17 13:41:24',
    openedLessonsCount: '2',
    completedDate: 'N/A',
    completedLessonsCount: 1,
    totalLessonsCount: 6,
    haveNotStarted: 'N/A',
    notOnSchedule: 'N/A',
    haveStarted: 'N/A',
    quizScore: 0,
    quizScoreTotal: 8,
    certificateTitle: 'N/A',
  },
  {
    project: 'Self Service',
    course: 'test - copy',
    person: 'Lukasz',
    email: 'lukasz@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2020-06-18 12:09:30',
    openedLessonsCount: '1',
    completedDate: '2020-06-18 12:10:30',
    completedLessonsCount: 1,
    totalLessonsCount: 1,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 1,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'test private project',
    person: 'Anonymous user',
    email: '',
    department: '',
    location: '',
    courseStartedDate: '2021-01-22 08:30:24',
    openedLessonsCount: '2',
    completedDate: 'N/A',
    completedLessonsCount: 0,
    totalLessonsCount: 2,
    haveNotStarted: 'N/A',
    notOnSchedule: 'N/A',
    haveStarted: 'N/A',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: 'N/A',
  },
  {
    project: 'Self Service',
    course: 'test private project',
    person: 'luk2',
    email: 'lukeon2+2@gmail.com',
    department: '',
    location: '',
    courseStartedDate: '2021-01-21 15:12:57',
    openedLessonsCount: '1',
    completedDate: '',
    completedLessonsCount: 0,
    totalLessonsCount: 1,
    haveNotStarted: '0',
    notOnSchedule: '1',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'test private project',
    person: 'Lukasz',
    email: 'l.jarmulowicz@gmail.com',
    department: '',
    location: '',
    courseStartedDate: '2021-01-21 15:15:31',
    openedLessonsCount: '1',
    completedDate: '',
    completedLessonsCount: 0,
    totalLessonsCount: 1,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Visio 2013',
    person: 'Lukasz',
    email: 'lukasz@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2019-04-15 06:55:57',
    openedLessonsCount: '2',
    completedDate: '',
    completedLessonsCount: 0,
    totalLessonsCount: 5,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Windows 10',
    person: 'Lukasz',
    email: 'lukasz@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2020-02-28 16:37:39',
    openedLessonsCount: '1',
    completedDate: '',
    completedLessonsCount: 1,
    totalLessonsCount: 11,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Windows 10',
    person: 'Lukasz',
    email: 'l.jarmulowicz@gmail.com',
    department: '',
    location: '',
    courseStartedDate: '2019-03-14 10:31:55',
    openedLessonsCount: '5',
    completedDate: '',
    completedLessonsCount: 3,
    totalLessonsCount: 11,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: 'Self Service',
    course: 'Word 2016',
    person: 'Lukasz',
    email: 'l.jarmulowicz@gmail.com',
    department: '',
    location: '',
    courseStartedDate: '2019-01-23 17:38:39',
    openedLessonsCount: '2',
    completedDate: '',
    completedLessonsCount: 1,
    totalLessonsCount: 16,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: 'ssl1',
    course: 'test - copy',
    person: 'Lukasz',
    email: 'l.jarmulowicz@gmail.com',
    department: '',
    location: '',
    courseStartedDate: '',
    openedLessonsCount: '0',
    completedDate: '',
    completedLessonsCount: 0,
    totalLessonsCount: 1,
    haveNotStarted: '1',
    notOnSchedule: '1',
    haveStarted: '0',
    quizScore: 0,
    quizScoreTotal: 1,
    certificateTitle: null,
  },
  {
    project: 'stat1',
    course: 'Kundeservice i Dynamics CRM',
    person: 'luk2',
    email: 'lukeon2+2@gmail.com',
    department: '',
    location: '',
    courseStartedDate: '2020-04-28 08:21:19',
    openedLessonsCount: '2',
    completedDate: '',
    completedLessonsCount: 2,
    totalLessonsCount: 9,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 0,
    certificateTitle: null,
  },
  {
    project: 'test - copy',
    course: 'test - copy',
    person: 'luk2',
    email: 'lukeon2+2@gmail.com',
    department: '',
    location: '',
    courseStartedDate: '2021-05-04 14:14:03',
    openedLessonsCount: '1',
    completedDate: '',
    completedLessonsCount: 1,
    totalLessonsCount: 3,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 2,
    certificateTitle: null,
  },
  {
    project: 'test prod vm',
    course: 'test - copy',
    person: 'luk2',
    email: 'lukeon2+2@gmail.com',
    department: '',
    location: '',
    courseStartedDate: '2021-01-29 15:14:58',
    openedLessonsCount: '3',
    completedDate: '2021-01-29 15:17:50',
    completedLessonsCount: 3,
    totalLessonsCount: 3,
    haveNotStarted: '0',
    notOnSchedule: '0',
    haveStarted: '1',
    quizScore: 1,
    quizScoreTotal: 1,
    certificateTitle: null,
  },
  {
    project: 'test0309-pas1',
    course: 'test - copy',
    person: 'Lukasz',
    email: 'lukasz@xtramile.no',
    department: '',
    location: '',
    courseStartedDate: '2020-09-21 12:49:55',
    openedLessonsCount: '1',
    completedDate: '',
    completedLessonsCount: 0,
    totalLessonsCount: 1,
    haveNotStarted: '0',
    notOnSchedule: '1',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 1,
    certificateTitle: null,
  },
  {
    project: 'test0309-pas1',
    course: 'test - copy',
    person: 'Lukasz',
    email: 'l.jarmulowicz@gmail.com',
    department: '',
    location: '',
    courseStartedDate: '2020-09-03 17:03:13',
    openedLessonsCount: '1',
    completedDate: '',
    completedLessonsCount: 0,
    totalLessonsCount: 1,
    haveNotStarted: '0',
    notOnSchedule: '1',
    haveStarted: '1',
    quizScore: 0,
    quizScoreTotal: 1,
    certificateTitle: null,
  },
];
export default menu;
